import 'package:flutter/material.dart';
import 'package:flutter_tdd/core/bloc/generic_cubit/generic_cubit.dart';
import 'package:flutter_tdd/core/theme/colors/colors_extension.dart';
import 'package:flutter_tdd/core/widgets/default_app_bar.dart';
import 'package:flutter_tdd/features/user/category/domain/entities/generic_params.dart';
import 'package:flutter_tdd/features/user/customers_products/domain/models/customer_product_details.dart';
import 'package:flutter_tdd/features/user/customers_products/domain/use_cases/get_customer_product_details.dart';
part 'customer_product_details.dart';
part 'customer_product_details_controller.dart';