/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String animation_lkb5jn5s = "assets/anims/animation_lkb5jn5s.json";
  static const String apple = "assets/images/apple.svg";
  static const String appLoaderBg = "assets/images/appLoaderBg.png";
  static const String ar = "assets/lang/ar.json";
  static const String arrow = "assets/images/arrow.svg";
  static const String blog = "assets/images/blog.png";
  static const String emptyCart = "assets/images/emptyCart.png";
  static const String en = "assets/lang/en.json";
  static const String facebook = "assets/images/facebook.svg";
  static const String logo = "assets/images/logo.png";
  static const String logoSvg = "assets/images/logoSvg.svg";
  static const String marker = "assets/images/marker.png";
  static const String mobile = "assets/images/mobile.svg";
  static const String myProfile = "assets/images/myProfile.png";
  static const String NotoSans = "assets/fonts/NotoSans.ttf";
  static const String offline = "assets/images/offline.png";
  static const String password = "assets/images/password.svg";
  static const String pdf = "assets/images/pdf.png";
  static const String placeHolder = "assets/images/placeHolder.png";
  static const String profile = "assets/images/profile.png";
}
