/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String animation_lkb5jn5s =
      "assets/anims/animation_lkb5jn5s.json";
  static const String apple = "assets/images/apple.svg";
  static const String appLoaderBg = "assets/images/appLoaderBg.png";
  static const String ar = "assets/lang/ar.json";
  static const String arrow = "assets/images/arrow.svg";
  static const String blog = "assets/images/blog.png";
  static const String emptyCart = "assets/images/emptyCart.png";
  static const String en = "assets/lang/en.json";
  static const String facebook = "assets/images/facebook.svg";
  static const String logo = "assets/images/logo.png";
  static const String logoPng = "assets/images/logo_png.png";
  static const String logoSvg = "assets/images/logoSvg.svg";
  static const String marker = "assets/images/marker.png";
  static const String mobile = "assets/images/mobile.svg";
  static const String myProfile = "assets/images/myProfile.png";
  static const String NotoSans = "assets/fonts/NotoSans.ttf";
  static const String offline = "assets/images/offline.png";
  static const String password = "assets/images/password.svg";
  static const String pdf = "assets/images/pdf.png";
  static const String placeHolder = "assets/images/placeHolder.png";
  static const String profile = "assets/images/profile.png";
  static const String faceLogo = "assets/images/face_logo.png";
  static const String google = "assets/images/google.png";
  static const String arrowBack = "assets/images/arrow_back.png";
  static const String forgetLogo = "assets/images/forget_logo.png";
  static const String splashLogo = "assets/images/splash_logo.png";
  static const String downloadLogo = "assets/images/download_logo.png";
  static const String returnOrdersLogo = "assets/images/return_orders_logo.png";
  static const String blogLogo = "assets/images/blog_logo.png";
  static const String wishListLogo = "assets/images/wish_list_logo.png";
  static const String compareLogo = "assets/images/compare_logo.png";
  static const String trackOrderLogo = "assets/images/track_order_logo.png";
  static const String walletLogo = "assets/images/wallet_logo.png";
  static const String ticketLogo = "assets/images/support_ticket_logo.png";

  static const String home = "assets/images/home.svg";
  static const String offers = "assets/images/offers.svg";
  static const String account = "assets/images/account.svg";
  static const String category = "assets/images/category.svg";
  static const String bgTabs = "assets/images/bgTabs.svg";
  static const String arrowMore = "assets/images/arrow_more.svg";
  static const String notification = "assets/images/notification.svg";
  static const String cart = "assets/images/cart.svg";
  static const String sortLogo = "assets/images/sort_logo.png";
  static const String search = "assets/images/search.svg";
  static const String flashSaleLogo = "assets/images/flash_sale_logo.png";
  static const String scaffBg1 = "assets/images/scaffBg1.svg";
  static const String scaffBg2 = "assets/images/scaffBg2.svg";

// ---------------------------Fonts-------------------------------------
  static const String notoSans = "assets/fonts/NotoSans.ttf";
  static const String quicksand = "assets/fonts/Quicksand.ttf";
}
