import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_tdd/core/bloc/generic_cubit/generic_cubit.dart';
import 'package:flutter_tdd/core/constants/dimens.dart';
import 'package:flutter_tdd/core/constants/gaps.dart';
import 'package:flutter_tdd/core/helpers/country_picker_helper.dart';
import 'package:flutter_tdd/core/helpers/validator.dart';
import 'package:flutter_tdd/core/localization/localization_methods.dart';
import 'package:flutter_tdd/core/routes/router_imports.gr.dart';
import 'package:flutter_tdd/core/theme/colors/colors_extension.dart';
import 'package:flutter_tdd/core/theme/text/app_text_style.dart';
import 'package:flutter_tdd/core/widgets/GenericTextField.dart';
import 'package:flutter_tdd/core/widgets/LoadingButton.dart';
import 'package:flutter_tdd/core/widgets/custom_radio_widget.dart';
import 'package:flutter_tdd/features/general/auth/presentation/manager/extensions/email_field_extension.dart';
import 'package:flutter_tdd/features/general/auth/presentation/widgets/build_input_label.dart';
import 'package:flutter_tdd/res.dart';

import '../login_imports.dart';

part'build_do_not_have_account.dart';
part 'build_forget_password_view.dart';
part 'build_login_button.dart';
part 'build_login_form.dart';
part 'build_login_social_media.dart';
part 'build_login_tabs.dart';
part 'build_login_tabs_view.dart';
part 'build_login_view.dart';
part 'build_social_item.dart';
part 'build_discount_dialog.dart';
part 'switch_phone_email_widget.dart';
part 'phone_filed_widget.dart';